CREATE TABLE IF NOT EXISTS users (
    user_id INT NOT NULL AUTO_INCREMENT,
    login VARCHAR(45) NOT NULL,
    reg_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
)  ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS planes (
    plane_id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    sits INT NOT NULL,
    PRIMARY KEY (plane_id)
)  ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS tickets (
    ticket_id INT NOT NULL AUTO_INCREMENT,
    cost INT NOT NULL,
    PRIMARY KEY (ticket_id)
)  ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS flights (
    flight_id INT NOT NULL AUTO_INCREMENT,
    plane_id INT NOT NULL,
    ticket_id INT NOT NULL,
    from_city VARCHAR(45) NOT NULL,
    to_city VARCHAR(45) NOT NULL,
    begin_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (flight_id),
    FOREIGN KEY (plane_id) REFERENCES planes(plane_id),
    FOREIGN KEY (ticket_id) REFERENCES tickets(ticket_id)
)  ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS payments (
    payment_id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    flight_id INT NOT NULL,
    payment_sum DOUBLE,
    payment_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (payment_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (flight_id) REFERENCES flights(flight_id)
)  ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS sessions (
    session_id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    begin_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_dttm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (session_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
)  ENGINE=INNODB AUTO_INCREMENT=1;